package com.example.demo.Book;

import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.List;

@Configuration
public class BookConfig {
    @Bean
    CommandLineRunner commandLineRunnerBook(BookRepository repository){
        return args -> {
            Book b1 = new Book(
                    "Hamlet",
                    "Shakespeare",
                    "Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.", true
            );

            Book b2 = new Book(
                    "Romeo i Julia",
                    "Shakespeare",
                    "Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.", true
            );
            Book b3 = new Book(
                    "Makbet",
                    "Shakespeare",
                    "Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna ru.", false
            );
            Book b4 = new Book(
                    "Makbet",
                    "Shakespeare",
                    "Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.", false
            );
            Book b5 = new Book(
                    "Buszujacy w Zbozu",
                    "J. D. Salinger",
                    "Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.", false
            );
            Book b6 = new Book(
                    "Pan Tadeusz",
                    "Adam Mickiewicz",
                    "Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.", false
            );
            Book b7 = new Book(
                    "Witcher",
                    "Andrzej Sapkowski",
                    "Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.", false
            );
            Book b8 = new Book(
                    "Hobbit",
                    "J. R. R. Tolkien",
                    "Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.", false
            );
            Book b9 = new Book(
                    "Harry Potter",
                    "J. K. Rowling",
                    "Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.", false
            );
            Book b10 = new Book(
                    "The Silmarillion",
                    "J. R. R. Tolkien",
                    "Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.", false
            );
            Book b11 = new Book(
                    "Hamlet",
                    "Shakespeare",
                    "Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.", false
            );
            Book b12 = new Book(
                    "Hamlet",
                    "Shakespeare",
                    "Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.", false
            );
            Book b13 = new Book(
                    "Where the wild things are",
                    "Maurice Sendak",
                    "Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.Praesent luctus tincidunt consectetur. Sed pulvinar, magna nec auctor imperdiet, urna orci malesuada erat, nec convallis lorem ex in odio. Curabitur semper iaculis varius. Pellentesque vitae orci purus. Cras a tincidunt magna. Nunc sem quam, lobortis vitae urna rutrum, mattis sollicitudin quam. Donec euismod, turpis ut placerat pretium, dui erat euismod nulla, vitae scelerisque orci velit quis erat. Sed pellentesque iaculis massa.", false
            );

            repository.saveAll(
                    List.of(b1,b2,b3,b4,b5,b6,b7,b8,b9,b10,b11,b12,b13)
            );

        };
    }
}
